name: Main workflow
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v4
      - name: Display directory
        uses: ./.github/workflows/workflow-actions
        with:
          command_to_execute: 'uname -a'
