name: Main workflow
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-slim
    steps:
      - name: Display directory
        uses: ./.github/actions/workflow-actions
        with:
          command_to_execute: 'ls -all'
      - name: Make directory
        uses: ./.github/actions/workflow-actions
        with:
          command_to_execute: 'mkdir abc'
       - name: Display directory 2
        uses: ./.github/actions/workflow-actions
        with:
          command_to_execute: 'ls -all'
